version: "3.3"
services:

  sui:
    container_name: NewTab
    restart: always
    build:
      context: ./
    environment:
      - VIRTUAL_HOST=test.laserr.net
    ports:
      - 8015:80
    volumes:
      - ./:/opt/html
