services:
  newtab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newtab
    restart: unless-stopped
    volumes:
      - ./:/var/www/html:Z
    ports:
      - 8015:80
    privileged: true
