version: '3'
services:
  NewTab:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: NewTab
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - 8015:80
